server:
  port: 80

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:db
    username: euller
    password: 12345
    driverClassName: org.h2.Driver


